config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root                    'events#index'
  get    '/login',   to:  'sessions#new'
  post   '/login',   to:  'sessions#create'
  delete '/logout',  to:  'sessions#destroy'
  resources :events, only: [:index, :new, :create, :show] do 
    resources :invitations, only: [:new, :create, :destroy]
  end
  resources :users, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :invitations, foreign_key: "attended_event_id"
  has_many :attendees, through: :invitations
  scope :upcoming_events, -> { where("date >= ?",DateTime.now)}
  scope :previous_events, -> { where("date < ?",DateTime.now)}
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
  validates :attendee, presence: true, uniqueness: {scope: :attended_event, message: "user is already an attendee for that event"}
  validates :attended_event, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :invitations, foreign_key: "attendee_id"
  has_many :events, foreign_key: "creator_id"
  has_many :attended_events, through: :invitations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      @events = Event.all
      render 'index'
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @invitation = Invitation.new
    if current_user.nil?
      @authorized_inviter = false
    elsif @event.creator_id == current_user.id
      @authorized_inviter = true
    else 
      @authorized_inviter = false
    end
  end

  def edit
  end

  def destroy
  end

  private

    def event_params
      params.require(:event).permit(:date, :description, :location)
    end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :find_invitation, only: :destroy
  
  def create
    @event = Event.find_by(id: invitation_params[:event].to_i)
    @attendee = User.find_by(username: invitation_params[:attendee])
    begin
      @event.attendees << @attendee
    rescue
      redirect_back(fallback_location: root_path) and return
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    if current_user.nil?
      @authorized_inviter = false
    elsif @event.creator_id == current_user.id
      @authorized_inviter = true
    else 
      @authorized_inviter = false
    end
    if @authorized_inviter == true
      @event.invitations.delete_by(attendee_id: @attendee)
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def invitation_params
    params.require(:invitation).permit(:event, :attendee)
  end

  def find_invitation
    @attendee = User.find_by(id: params[:id])
    @event = Event.find_by(id: params[:event_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    log_in user
    redirect_to root_url
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:username)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module  SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user
    User.find_by(id: (session[:user_id]))
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<div class="primary-fields">
  <%= form_with(model: event, local: true) do |form| %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
          <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :date %>
      <%= form.date_field :date %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_field :description %>
    </div>

    <div class="field">
      <%= form.label :location %>
      <%= form.text_field :location %>
    </div>

    <div class="actions">
      <% if !session[:user_id].nil? %>
        <%= form.submit class: "btn btn-primary" %>
      <% else %>
        <p>Cannot submit a new event unless you are logged in.</p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>
<hr>
<h2>Upcoming Events</h2>
  <% if @events.upcoming_events.blank? %>
    <p>No upcoming events at this time.</p>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Description</th>
          <th>Location</th>
          <th>Creator</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
          <% @events.upcoming_events.each do |event| %>
            <tr>
              <td><%= event.date %>
              <td><%= link_to event.description, "events/#{event.id}" %></td>
              <td><%= event.location %></td>
              <td><%= event.creator.username %></td>
            </tr>
          <% end %>
      </tbody>
    </table>
  <% end %>
  <br>
<%= link_to 'New Event', new_event_path, class: "btn btn-primary", id: "new-event-btn" %>
<hr>
<h2>Previous Events</h2>
<% if @events.previous_events.blank? %>
    <p>No previous events at this time.</p>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Description</th>
          <th>Location</th>
          <th>Creator</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @events.previous_events.each do |event| %>
          <tr>
            <td><%= event.date %>
            <td><%= link_to event.description, "events/#{event.id}" %></td>
            <td><%= event.location %></td>
            <td><%= event.creator.username %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

<br>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @event.creator.username %>
</p>

<table class="table">
  <tr>
    <th>Attendees</th><th></th>
  </tr>
  <% if @event.attendees.blank? %>
    <td> -Nobody has been invited yet- </td>
  <% else %>
    <% @event.attendees.each do |attendee| %>
      <tr>
      <td><%= attendee.username %></td>
      <% if @authorized_inviter == true %>
        <td><%= link_to 'Uninvite', "#{@event.id}/invitations/#{attendee.id}", method: 'delete' %>
      <% end %>
      </tr>
    <% end %>
  <% end %>
</table>
<div>
  <% if @authorized_inviter == true %>
    <%= form_with(model: @invitation, url: "/events/#{@event.id}/invitations", method: 'post', local: true) do |form| %>
      <div class = "hidden-field">
        <%= form.hidden_field :event, value: @event.id %>
      </div>
      <div class="field">
        <%= form.label :attendee %>
        <%= form.text_field :attendee %>
      </div>
      <div class="actions">
        <%= form.submit class: "btn" %>
      </div>
    <% end %>
  <% end %>
</div>

<%= link_to 'Back', events_path %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
   <%= link_to "Private Events", '/', id: "logo" %>
   <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Events",     '/events' %></li>
       <% if !session[:user_id].nil? %>
        <li><%= link_to "New event",  '/events/new'%></li>
        <li><%= link_to "#{User.find_by(id: session[:user_id]).username}'s Profile", current_user %></li>
        <li><%= link_to "Sign out",   '/logout', method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign up",    '/users/new' %></li>
        <li><%= link_to "Log in",     '/login' %></li>
      <% end %>
   </ul>
  </nav>
 </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>
  <hr>
<h2><%= @user.username %> is hosting the following events:</h2>
  <% if @user.events.empty? %>
    <p>None at this time.</p>
  <% else %>
    <table class="table">
    <tr>
      <th>Date</th>
      <th>Description</th>
      <th>Location</th>
    </tr>
    <% @user.events.each do |e| %>
      <tr>
        <td><%= e.date %></td>
        <td><%= link_to e.description, e %></td>
        <td><%= e.location %></td>
      </tr>
    <% end %>
    </table>
  <% end %>
<h2><%= @user.username %> is attending the following events:</h2>
  <% if @user.attended_events.empty? %>
    <p>None at this time.</p>
  <% else %>
    <table class="table">
    <tr>
      <th>Date</th>
      <th>Description</th>
      <th>Location</th>
    </tr>
    <% @user.attended_events.each do |e| %>
      <tr>
        <td><%= e.date %></td>
        <td><%= e.description %></td>
        <td><%= e.location %></td>
      </tr>
    <% end %>
    </table>
  <% end %>

<%= link_to 'Back', users_path %>